[pytest]
addopts = 
         --html=reports/report.html
         -v --html=report.html --self-contained-html

testpaths = 
         tests
markers =
        smoke: critical tests
         regression: full test suite