[pytest]

addopts =
    -v
    --tb=short
    --html=reports/report.html
    --self-contained-html

testpaths =
    tests

markers =
    smoke: critical tests
    regression: full test suite
    cart: cart tests
    checkout: checkout tests
    login: login tests